config/routes.rb
Rails.application.routes.draw do
  devise_for :super_admins
  resources :choices
  resources :elections
  devise_for :electors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :election
end

app/models/election.rb
class Election < ApplicationRecord
    has_many :choices
end

app/models/elector.rb
class Elector < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/super_admin.rb
class SuperAdmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :firstname, :groupes])
  end
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  before_action :set_choice, only: [:show, :edit, :update, :destroy]

  # GET /choices
  # GET /choices.json
  def index
    @choices = Choice.all
  end

  # GET /choices/1
  # GET /choices/1.json
  def show
  end

  # GET /choices/new
  def new
    @choice = Choice.new
  end

  # GET /choices/1/edit
  def edit
  end

  # POST /choices
  # POST /choices.json
  def create
    @choice = Choice.new(choice_params)

    respond_to do |format|
      if @choice.save
        format.html { redirect_to @choice, notice: 'Choice was successfully created.' }
        format.json { render :show, status: :created, location: @choice }
      else
        format.html { render :new }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /choices/1
  # PATCH/PUT /choices/1.json
  def update
    respond_to do |format|
      if @choice.update(choice_params)
        format.html { redirect_to @choice, notice: 'Choice was successfully updated.' }
        format.json { render :show, status: :ok, location: @choice }
      else
        format.html { render :edit }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /choices/1
  # DELETE /choices/1.json
  def destroy
    @choice.destroy
    respond_to do |format|
      format.html { redirect_to choices_url, notice: 'Choice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_choice
      @choice = Choice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def choice_params
      params.require(:choice).permit(:name, :election_id)
    end
end

app/controllers/concerns/accessible.rb
module Accessible
    extend ActiveSupport::Concern
    included do
      before_action :check_user
    end
  
    protected
    def check_user
      if current_super_admin
        flash.clear
        redirect_to(elections_path) && return
      elsif current_elector
        flash.clear
        redirect_to(root_path) && return
      end
    end
end

app/controllers/elections_controller.rb
class ElectionsController < ApplicationController
  before_action :set_election, only: [:show, :edit, :update, :destroy]

  # GET /elections
  # GET /elections.json
  def index
    @elections = Election.all
  end

  # GET /elections/1
  # GET /elections/1.json
  def show
    @choices = @election.choices
  end

  # GET /elections/new
  def new
    @election = Election.new
  end

  # GET /elections/1/edit
  def edit
  end

  # POST /elections
  # POST /elections.json
  def create
    choices_names = params[:election]['choices']
    @election = Election.new(election_params)
    
    if @election.save
      choices_names.each do |name|
        Choice.new(name: name, election_id: @election.id).save
      end
    end

    respond_to do |format|
      if @election.save
        format.html { redirect_to @election, notice: 'Election was successfully created.' }
        format.json { render :show, status: :created, location: @election }
      else
        format.html { render :new }
        format.json { render json: @election.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elections/1
  # PATCH/PUT /elections/1.json
  def update
    respond_to do |format|
      if @election.update(election_params)
        format.html { redirect_to @election, notice: 'Election was successfully updated.' }
        format.json { render :show, status: :ok, location: @election }
      else
        format.html { render :edit }
        format.json { render json: @election.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elections/1
  # DELETE /elections/1.json
  def destroy
    @election.destroy
    respond_to do |format|
      format.html { redirect_to elections_url, notice: 'Election was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_election
      @election = Election.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def election_params
      params.require(:election).permit(:start_date, :end_date, :groups, :title, :choices)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def index
        if elector_signed_in?
            @elections = Election.all.where(groups: current_elector.groups)
        elsif super_admin_signed_in?
            @elections = Election.all
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/elections_helper.rb
module ElectionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/choices/_form.html.erb
<%= form_with(model: choice, local: true) do |form| %>
  <% if choice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(choice.errors.count, "error") %> prohibited this choice from being saved:</h2>

      <ul>
      <% choice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :election_id %>
    <%= form.text_field :election_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/choices/edit.html.erb
<h1>Editing Choice</h1>

<%= render 'form', choice: @choice %>

<%= link_to 'Show', @choice %> |
<%= link_to 'Back', choices_path %>

app/views/choices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Choices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Election</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @choices.each do |choice| %>
      <tr>
        <td><%= choice.name %></td>
        <td><%= choice.election %></td>
        <td><%= link_to 'Show', choice %></td>
        <td><%= link_to 'Edit', edit_choice_path(choice) %></td>
        <td><%= link_to 'Destroy', choice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Choice', new_choice_path %>

app/views/choices/new.html.erb
<h1>New Choice</h1>

<%= render 'form', choice: @choice %>

<%= link_to 'Back', choices_path %>

app/views/choices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @choice.name %>
</p>

<p>
  <strong>Election:</strong>
  <%= @choice.election %>
</p>

<%= link_to 'Edit', edit_choice_path(@choice) %> |
<%= link_to 'Back', choices_path %>

app/views/elections/_form.html.erb
<%= form_with(model: election, local: true) do |form| %>
  <% if election.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(election.errors.count, "error") %> prohibited this election from being saved:</h2>

      <ul>
      <% election.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :groups %>
    <%= select_tag :groups, options_for_select([ "All", "Compta", "IT" ]) %>
  </div>

  <div class="field choices-field">
    <label>Choices <a href="#" class="add-choice">Ajouter un choix</a></label>
    <br>
    <% fields_for :choices do |f| %>
      <%= f.text_field :choices %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/elections/edit.html.erb
<h1>Editing Election</h1>

<%= render 'form', election: @election %>

<%= link_to 'Show', @election %> |
<%= link_to 'Back', elections_path %>

app/views/elections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Elections</h1>

<table class="table">
  <thead>
    <tr>
      <th>Start date</th>
      <th>End date</th>
      <th>Groups</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @elections.each do |election| %>
      <tr>
        <td><%= election.start_date %></td>
        <td><%= election.end_date %></td>
        <td><%= election.groups %></td>
        <td><%= election.title %></td>
        <td><%= link_to 'Show', election %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/elections/new.html.erb
<h1>New Election</h1>

<%= render 'form', election: @election %>

<%= link_to 'Back', elections_path %>

app/views/elections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @election.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @election.end_date %>
</p>

<p>
  <strong>Groups:</strong>
  <%= @election.groups %>
</p>

<p>
  <strong>Choices:</strong>
  <% @choices.each do |choice| %>
    <%= radio_button_tag "new_vote", choice.name %>
    <%= choice.name %>
  <% end %>
  <%= submit_tag "Voter", class: "btn btn-primary" %>
</p>

<p>
  <strong>Title:</strong>
  <%= @election.title %>
</p>

<%= link_to 'Edit', edit_election_path(@election) if super_admin_signed_in? %> |
<%= link_to 'Back', root_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light navbar-expand-lg" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="#">voteGO</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/elections">Elections</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/super_admins/sign_in">Admins</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InfraDev</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Bonjour <%= current_elector.email if elector_signed_in? %></h1>

<%= flash[:notice] %>
<%= flash[:alert] %>

<p>Aujourd'hui, vous allez voter.</p>

<% if super_admin_signed_in? %>
    <p>ADMIN MODE</p>
<% end %>

<p>
<%=
link_to_unless(elector_signed_in?, "Login", new_elector_session_path) do
    link_to('Deconnexion', destroy_elector_session_path, method: :delete)
end
%>
</p>

<p>
    <% if elector_signed_in? || super_admin_signed_in? %>
        <% if @elections.nil? %>
            <p>Il n'y a pas d'élections pour le moment</p>
        <% else %>
            <h2>Liste des élections en cours</h2>
            <table class="table">
                <thead>
                    <tr>
                    <th>Start date</th>
                    <th>End date</th>
                    <th>Title</th>
                    <th colspan="3"></th>
                    </tr>
                </thead>

                <tbody>
                    <% @elections.each do |election| %>
                    <tr>
                        <td><%= election.start_date %></td>
                        <td><%= election.end_date %></td>
                        <td><%= election.title %></td>
                        <td><%= link_to 'Show', election %></td>
                        <% if super_admin_signed_in? %>
                        <td><%= link_to 'Edit', edit_election_path(election) %></td>
                        <td><%= link_to 'Destroy', election, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        <% end %>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        <% end %>
    <% end %>
</p>

app/views/super_admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>